[project]
authors = ["sweetpeteza <peter@playbk.io>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "day01-part01"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
python = "3.11.*"
